config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/hot', to: 'static_pages#hot', via: 'get'
  match '/week', to: 'static_pages#week', via: 'get'
  match '/free', to: 'static_pages#free', via: 'get'
  

end

app/models/dotw.rb
class Dotw < ActiveRecord::Base
	belongs_to :retailer
	validates :content, presence: true
end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
	has_many :dotws, dependent: :destroy
	before_save { self.name = name.downcase }
	validates :name, presence: true, length: { maximum: 20 }, 
				     uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence:true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  					  uniqueness: { case_sensitive: false }
  	has_secure_password
  	validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def hot
  end

  def week
  	@bestbuy = Retailer.find_by(name: "bestbuy")
  	@ebgames = Retailer.find_by(name: "eb games")
  	@futureshop = Retailer.find_by(name: "future shop")
  	@target = Retailer.find_by(name: "target")
  	@thesource = Retailer.find_by(name: "the source")
  	@walmart = Retailer.find_by(name: "wal-mart")
  	@psn = Retailer.find_by(name: "psn")
  	@xboxlive = Retailer.find_by(name: "xbox live")
  end

  def free
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "The Tavern"
		"#{base_title} | #{page_title}"
	end

end

app/helpers/dotws_helper.rb
module DotwsHelper

	# the following was for testing purposes and is not used
	def platform(x)
		if (x.include?("PS4 XONE WU PS3 360 WII 3DS VITA"))
			 return "PS4 XONE WU PS3 360 WII 3DS VITA"
		end
		
		if (x.include?("PS4 XONE WU PS3 360 WII 3DS"))
			 return "PS4 XONE WU PS3 360 WII 3DS"
		end
		
		if (x.include?("PS4 XONE WU PS3 360 WII"))
			 return "PS4 XONE WU PS3 360 WII"
		end
		
		if (x.include?("PS4 XONE WU PS3 360"))
			 return "PS4 XONE WU PS3 360"
		end
		
		if (x.include?("PS4 XONE WU PS3"))
			 return "PS4 XONE WU PS3"
		end
		
		if (x.include?("PS4 XONE WU"))
			 return "PS4 XONE WU"
		end
		
		if (x.include?("PS4 XONE"))
			 return "PS4 XONE"
		end
		
		if (x.include?("PS4"))
			 return "PS4"
		end

		if x.include? "XONE"
			print "XONE"
		end

		if x.include? "WU"
			print "WII U"
		end

		if x.include? "PS3"
			print "PS3"
		end

		if x.include? "360"
			print "360"
		end

		if x.include? "WII"
			print "WII"
		end

		if x.include? "3DS"
			print "3DS"
		end

		if x.include? "Vita"
			print "Vita"
		end
	end
	
	def thissucks()
		"ppp"
	end
	
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="navbar-font">*Facebook Icon*</li>
        <li class="navbar-font">*Twitter Icon*</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li class="navbar-font"><a href="#">Terms of Use</a></li>
        <li class="navbar-font"><a href="#">Contact Us</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://google.com"><span class="glyphicon glyphicon-home"></span> <strong>THE TAVERN</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="navbar-font"><%= link_to "Hot Deals", hot_path %></li>
        <li class="navbar-font"><%= link_to "Deals of the Week", week_path %></h1></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-font"><a href="#">Sign in</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap -->
		<link href="css/bootstrap.min.css" rel="stylesheet">

		<%= render 'layouts/shim' %>
	
  		<title><%= full_title(yield(:title)) %></title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class = "container">
			<%= render 'layouts/header' %>
	
			<%= yield %>
			
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>

		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>

app/views/static_pages/free.html.erb
<% provide(:title, 'Freebies') %>
<h1>Freebies!</h1>
<p>
	List of free stuff by retailers
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Canadian Video Games Deals') %>
<h1>The Tavern</h1>
<p>
	The Tavern is dedicated to bringing you the hottest videogame
	deals in Canada.
	
	
	<br>
	<%= link_to "Hot Deals", hot_path, class: "btn btn-large btn-primary" %>
	
	<br>
	<%= link_to "Deals of the Week", week_path, class: "btn btn-large btn-primary" %>
	
	<br>
	<%= link_to "Freebies", free_path, class: "btn btn-large btn-primary" %>
	
	
	<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button>
	
	
</p>

app/views/static_pages/hot.html.erb
<% provide(:title, 'Hot Deals') %>
<h1>Hottest Deals</h1>
<p>
	Hottest deals of the moment
</p>

app/views/static_pages/week.html.erb
<% provide(:title, 'Deals of the Week') %>

<center><h1><strong>Deals of the Week</strong></h1><h5>(July 4th, 2014 - July 10th, 2014)</h5></center>

<!-- mini navbar -->
<ul class="nav nav-pills">
  <li><a href="#bestbuy"><%= image_tag "bestbuy_logo.png" %></a></li>
  <li><a href="#ebgames"><%= image_tag "ebgames_logo.png" %></a></li>
  <li><a href="#futureshop"><%= image_tag "futureshop_logo.png" %></a></li>
  <li><a href="#target"><%= image_tag "target_logo.png" %></a></li>
  <li><a href="#thesource"><%= image_tag "thesource_logo.png" %></a></li>
  <li><a href="#walmart"><%= image_tag "walmart_logo.png" %></a></li>
  <li><a href="#psn"><%= image_tag "psn_logo.png" %></a></li>
  <li><a href="#xboxlive"><%= image_tag "xboxlive_logo.png" %></a></li>
</ul>

<!-- start of accordion -->
<div class="panel-group" id="accordion">

<!-- Bestbuy -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseOne">
          <div id="bestbuy"> <%= @bestbuy.name.upcase %> (<%= @bestbuy.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @bestbuy.dotws.any? %>
      		<% (@bestbuy.dotws.ids).each do |i| %>
      			<ul>
      				<% if @bestbuy.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @bestbuy.dotws.find(i).content %></strong> <samp><%= @bestbuy.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @bestbuy.dotws.find(i).content %></strong> <samp><%= @bestbuy.dotws.find(i).platform %></samp> <span class="price">($<%= @bestbuy.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>	
      		<a href="#">Source</a>
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- EB Games -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseTwo">
          <div id="ebgames"> <%= @ebgames.name.upcase %> (<%= @ebgames.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @ebgames.dotws.any? %>
      		<% (@ebgames.dotws.ids).each do |i| %>
      			<ul>
      				<% if @ebgames.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @ebgames.dotws.find(i).content %></strong> <samp><%= @ebgames.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @ebgames.dotws.find(i).content %></strong> <samp><%= @ebgames.dotws.find(i).platform %></samp> <span class="price">($<%= @ebgames.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>	
      		<a href="#">Source</a>
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- Future Shop -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseThree">
          <div id="futureshop"> <%= @futureshop.name.upcase %> (<%= @futureshop.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @futureshop.dotws.any? %>
      		<% (@futureshop.dotws.ids).each do |i| %>
      			<ul>
      				<% if @futureshop.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @futureshop.dotws.find(i).content %></strong> <samp><%= @futureshop.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @futureshop.dotws.find(i).content %></strong> <samp><%= @futureshop.dotws.find(i).platform %></samp> <span class="price">($<%= @futureshop.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>	
      		<a href="#">Source</a>
      	<% end %>
       </div>
     </div>
  </div>
  
<!-- Target -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseFour">
          <div id="target"> <%= @target.name.upcase %> (<%= @target.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @target.dotws.any? %>
      		<% (@target.dotws.ids).each do |i| %>
      			<ul>
      				<% if @target.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @target.dotws.find(i).content %></strong> <samp><%= @target.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @target.dotws.find(i).content %></strong> <samp><%= @target.dotws.find(i).platform %></samp> <span class="price">($<%= @target.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>
      		<a href="#">Source</a>	
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- The Source -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseFive">
          <div id="thesource"> <%= @thesource.name.upcase %> (<%= @thesource.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @thesource.dotws.any? %>
      		<% (@thesource.dotws.ids).each do |i| %>
      			<ul>
      				<% if @thesource.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @thesource.dotws.find(i).content %></strong> <samp><%= @thesource.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @thesource.dotws.find(i).content %></strong> <samp><%= @thesource.dotws.find(i).platform %></samp> <span class="price">($<%= @thesource.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>
      		<a href="#">Source</a>	
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- Wal-Mart -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseSix">
          <div id="walmart"> <%= @walmart.name.upcase %> (<%= @walmart.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @walmart.dotws.any? %>
      		<% (@walmart.dotws.ids).each do |i| %>
      			<ul>
      				<% if @walmart.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @walmart.dotws.find(i).content %></strong> <samp><%= @walmart.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @walmart.dotws.find(i).content %></strong> <samp><%= @walmart.dotws.find(i).platform %></samp> <span class="price">($<%= @walmart.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>	
      		<a href="#">Source</a>
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- PSN -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseSeven">
          <div id="psn"> <%= @psn.name.upcase %> (<%= @psn.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse in">
      <div class="panel-body">
        <% if @psn.dotws.any? %>
      		<% (@psn.dotws.ids).each do |i| %>
      			<ul>
      				<% if @psn.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @psn.dotws.find(i).content %></strong> <samp><%= @psn.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @psn.dotws.find(i).content %></strong> <samp><%= @psn.dotws.find(i).platform %></samp> <span class="price">($<%= @psn.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>	
      		<a href="#">Source</a>
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- XBOX Live -->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapseEight">
          <div id="xboxlive"> <%= @xboxlive.name.upcase %> (<%= @xboxlive.dotws.count %>)</div>
        </a>
      </h4>
    </div>
    <div id="collapseEight" class="panel-collapse collapse in">
      <div class="panel-body">
      	<% if @xboxlive.dotws.any? %>
      		<% (@xboxlive.dotws.ids).each do |i| %>
      			<ul>
      				<% if @xboxlive.dotws.find(i).price == 0.0 %>
      					<li><strong><%= @xboxlive.dotws.find(i).content %></strong> <samp><%= @xboxlive.dotws.find(i).platform %></samp></li>
      				<% else %>
      					<li><strong><%= @xboxlive.dotws.find(i).content %></strong> <samp><%= @xboxlive.dotws.find(i).platform %></samp> <span class="price">($<%= @xboxlive.dotws.find(i).price %>)</span></li>
      				<% end %>
      			</ul>	
      		<% end %>
      		<a href="#">Source</a>	
      	<% end %>
      </div>
    </div>
  </div>
  
<!-- end of accordion -->
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>